# -*- coding: utf-8 -*-
"""Data Structures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1He5g_-KOOVu1cKkaZQ57T397GxFN-Yz_

1. Write a code to create a string with your name and print it
"""

str="Bhanu"
print(str)

"""2. Write a code to find the length of the string "Hello World"
"""

s="Hello World"
len(s)

"""3. Write a code to slice the first 3 characters from the string "Python Programming"
"""

string="Python Programming"
string[0:3]

"""4. Write a code to convert the string "hello" to uppercase"""

text="hello"
text.upper()

"""5. Write a code to replace the word "apple" with "orange" in the string "I like apple"
"""

st="I like apple"
st.replace("apple","orange")

"""6. Write a code to create a list with numbers 1 to 5 and print it"""

l=[1,2,3,4,5]
print(l)

"""7. Write a code to append the number 10 to the list [1, 2, 3, 4]"""

list=[1,2,3,4]
list.append(10)
print(list)

"""8. Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]"""

l1=[1,2,3,4,5]
l1.remove(3)
print(l1)

"""9. Write a code to access the second element in the list ['a', 'b', 'c', 'd']"""

l2=['a','b','c','d']
l2[1]

"""10. Write a code to reverse the list [10, 20, 30, 40, 50]"""

l3=[10,20,30,40,50]
l3[::-1]

"""11. Write a code to create a tuple with the elements 100, 200, 300 and print it"""

t=(100,200,300)
print(t)

"""12. Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow')"""

tup=("red","green","blue","yellow")
tup[-2]

"""13. Write a code to find the minimum number in the tuple (10, 20, 5, 15)"""

tu=(10,20,5,15)
min(tu)

"""14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit')"""

tup=("dog","cat","rabbit")
tup.index("cat")

"""15. Write a code to create a tuple containing three different fruits and check if "kiwi" is in it"""

fruits=("apple","banana","kiwi")
"kiwi" in fruits

"""16. Write a code to create a set with the elements 'a', 'b', 'c' and print it."""

s={"a","b","c"}
print(s)

"""17. Write a code to clear all elements from the set {1, 2, 3, 4, 5}."""

s={1,2,3,4,5}
s.clear()
print(s)

"""18. Write a code to remove the element 4 from the set {1, 2, 3, 4}."""

s={1,2,3,4}
s.remove(4)
print(s)

"""19. Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}."""

s1={1,2,3}
s2={3,4,5}
print(s1 | s2)

"""20.  Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}"""

s1={1,2,3}
s2={2,3,4}
print(s1 & s2)

"""21. Write a code to create a dictionary with the keys "name", "age", and "city", and print it."""

d={"name":"bhanu","age":26,"city":"mumbai"}
print(d)

"""22. Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}."""

dic={'name': 'John', 'age': 25}
dic["country"]="USA"
print(dic)

"""23. Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}"""

d={'name': 'Alice', 'age': 30}
d.get("name")
#another way
d["name"]

"""24. Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}."""

d={'name': 'Bob', 'age': 22, 'city': 'New York'}
d.pop("age")
print(d)

"""25. Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}."""

d={'name':'Alice','city':'Paris'}
if "city" in d:
    print("exists")
else:
    print("not exists")

"""26. Write a code to create a list, a tuple, and a dictionary, and print them all."""

l=[1,3.4,True,5+6j,"Aman"]
print(l)
t=(1,2,3,4)
print(t)
d={"name":"bhanu","age":26}
print(d)

"""27. Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the
result.(replaced)
"""

l=[20,15,3,75,50]
sorted(l)

"""28. Write a code to create a list with strings and print the element at the third index"""

l=["Aman","Bhanu","Chetan","Dhruv"]
print(l[3])

"""29. Write a code to combine two dictionaries into one and print the result"""

d1={"name":"Bhanu","age":26}
d2={"city":"Mumbai","country":"India"}
d1.update(d2)
print(d1)

"""30. Write a code to convert a list of strings into a set."""

l={"Bhanu","Chetan","Dhruv"}
set(l)